In [1]:
import numpy as np

In [2]:
# 1:
arr = np.arange(10)
print(arr)
print(arr.dtype)
print(arr.size)

[0 1 2 3 4 5 6 7 8 9]
int32
10


In [3]:
# 2
arr_odd = arr[:]%2 ==0
print(f"arr_odd:\n{arr[arr_odd]}")
# arr_even = np.array([i for i in arr if i %2!= 0])
# print(f"arr_even:\n{arr_even}")
# cach 2:
arr_even = arr[~arr_odd]
print(f"arr_even:\n{arr_even}")

arr_odd:
[0 2 4 6 8]
arr_even:
[1 3 5 7 9]


In [4]:
# 3
arr_update_1 = np.where(arr[:]%2==0,arr,100)
print("arr_update_1:",arr_update_1)

arr_update_1: [  0 100   2 100   4 100   6 100   8 100]
