In [5]:
import numpy as np

In [13]:
arr_a = [1,2,3,2,3,4,3,4,5,6]
arr_b = [7,2,10,2,7,4,9,4,9,8]
# 1:
# cach 1:
# lst= []
# for i in arr_a:
#     if i in arr_b:
#         lst.append(i)
# print(lst)
# cach 2:
arr_c = np.array([i for i in arr_a if i in arr_b])
print(arr_c)

# 2:
arr_d = np.array([x for x in arr_a if x  not in arr_b])
print(arr_d)

# 3:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f  = arr_e[ (arr_e>=5) & (arr_e<=10)]
print(arr_f)

[2 2 4 4]
[1 3 3 3 5 6]
[ 6  9 10  8  6]
