In [1]:
import numpy as np
arr_zeros = np.zeros(10)
arr_zeros[4] = 1
arr_zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [2]:
arr_h = np.arange(10,25)
arr_h[::-1]


array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [3]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = np.array([i for i in arr_k if i!=0])
arr_l
add = [10,20]
arr_l_new = np.append(arr_l,add)
arr_l_new
arr_l_new_5 = np.insert(arr_l_new,5,100)
print(arr_l_new_5)
arr_l_new_6 = np.delete(arr_l_new_5,[0,1,2])
arr_l_new_6


[  1   2   8   2   1 100   3   5  10  20]


array([  2,   1, 100,   3,   5,  10,  20])