In [2]:
import numpy as np


In [3]:
# 1:
arr = np.full((3,3),fill_value=True)
arr


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# 2:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = arr_1D.reshape((3,3))
print(arr_2D)
arr_2D[:,::2] = arr_2D[:,::-2]
print("arr_2D_new:\n",arr_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_2D_new:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [5]:
# 3:
arr_2D[:,[0,1]] = arr_2D[:,[1,0]]
arr_2D

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [6]:
# 4:
arr_2D_4 =arr_2D[::-1]
arr_2D_4

array([[7, 8, 6],
       [4, 5, 3],
       [1, 2, 0]])

In [7]:
# 5:
arr_2D_5 = arr_2D_4[:,::-1]
arr_2D_5

array([[6, 8, 7],
       [3, 5, 4],
       [0, 2, 1]])

In [8]:
# 6:
arr_2D_null = np.array([[1, 2, 3],
                        [np.NaN, 5, 6],
                        [7, np.NaN, 9],
                        [4, 5, 6]])
# print("trong array có phần tử rỗng:",np.isnan(arr_2D_null).any())

In [10]:
# 7:
nan_=np.isnan(arr_2D_null)
arr_2D_null_7 = np.where(~nan_,arr_2D_null,0)
arr_2D_null_7


array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])